### ISSUE TITLE
Id_type for mouse genes

### ISSUE THREAD

**Issue by hkanya** [churchmanlab/genewalk#1]
I have a text file of mouse genes with its MGI_ID (e.g. MGI:894679). However when I ran genewalk I receive errors : genewalk.gene_lists - Could not get HGNC ID for MGI ID although the code kept running. Is this an issue and if so should I convert the gene names into HGNC ID instead?

**Comment by ri23** [comment]
Some expected numbers to compare your run with: we found that for ~5% of our 1861 input MGI ids no human HGNC ids were found in our study of mouse RNA-seq (see biorxiv paper for details). Hope this helps you interpret your results.

**Comment by bgyori** [comment]
Hi @hkanya, let us know if you are still having issues, otherwise I'll close this thread

**Comment by hkanya** [comment]
It's working now thank you!
