### ISSUE TITLE
Visualization of the results

### ISSUE THREAD

**Issue by chrarnold** [churchmanlab/genewalk#10]
Hi, I have a result table now, and I am wondering whether you or anyone else already has an R or Python script to visualize a GeneWalk result table in an automated fashion, similar to what you show in the publication. I can code it for myself, but why reinvent the wheel? :)

**Comment by ri23** [comment]
Hi @chrarnold , yes I can provide you some Python code to plot GO relevance scores bar charts for individual genes. I am thinking to add this to the GeneWalk tutorial to make it easily accessible to the public. I will work on that, thanks

**Comment by chrarnold** [comment]
I think this would be great and contribute largely to the success and usability of the tool. I am an R guy, I will try to add some R code. I am happy to share this once I have something nice.

**Comment by chrarnold** [comment]
But please share the Python code also, the Documentation sounds like the right place to do so. Honestly, an automated visualization as part of the genewalk workflow would be great also, so users  can directly visualize the results, in addition to the output table. Like a PDF with one page per gene or something, just something to get you started and excited. Similar visualizations than you used in the paper essentially.

**Comment by ri23** [comment]
The tutorial now has bar chart visualization Python code in a short jupyter notebook http://churchman.med.harvard.edu/genewalk We'll look into more automated visualization scripts at a later time.

**Comment by chrarnold** [comment]
Hi, I invested an hour yesterday to produce an R script that takes an output table from GeneWalk and mimics the plots you produced for the paper. It goes even a bit further and varies the fdr thresholds etc. Are you interested in having it and sharing it in the Tutorial?

**Comment by ri23** [comment]
Thank you for the suggestion to support plotting for R users. I have made some code to plot the same bar charts in R with ggplot2 in the tutorial. I kept it very similar to the Python code for simplicity.

**Comment by bgyori** [comment]
The tutorial now covers visualization with code samples in R and Python - should we close this issue?
