### ISSUE TITLE
ensembl_id

### ISSUE THREAD

**Issue by marttine** [churchmanlab/genewalk#17]
The documentation shows that genewalk supports ensembl_id. However, after simple installation (pip install genewalk) and a test run, it reports an error that ensembl_id is not supported. 

usage: genewalk [-h] --project PROJECT --genes GENES **--id_type
                {hgnc_symbol,hgnc_id,mgi_id**}
                [--stage {all,node_vectors,null_distribution,statistics}]
                [--base_folder BASE_FOLDER]
                [--network_source {pc,indra,edge_list,sif}]
                [--network_file NETWORK_FILE] [--nproc NPROC]
                [--nreps_graph NREPS_GRAPH] [--nreps_null NREPS_NULL]
                [--alpha_fdr ALPHA_FDR] [--save_dw SAVE_DW]
                [--random_seed RANDOM_SEED]

**Comment by ri23** [comment]
Hi @marttine 
The github repo is currently ahead of the python package in terms of support for ensembl ids. If you install genewalk using `pip install git+https://github.com/churchmanlab/genewalk.git` it should work. We will release an updated Python package in the near future to reflect these updates.
