### ISSUE TITLE
rdflib=4.2.2 and python 3 version conflict

### ISSUE THREAD

**Issue by tmargus** [churchmanlab/genewalk#26]
Hi,
I am using anaconda python ver 3.6
adding missing library

conda install -n py36 rdflib=4.2 

ends up with information about conflict between py3.6 and rdflib=4.2.2 
saying that  rdflib=4.2 -> python=3.4

Best,
Tõnu

**Comment by bgyori** [comment]
Hi @tmargus, the `rdflib==4.2.2` requirement comes from one of GeneWalk's dependencies but it is not essential to match exactly so you can ignore any warnings about the version conflicts. Just to be sure, is GeneWalk working otherwise?

**Comment by bgyori** [comment]
I'll close this for now, please reopen if there is still an issue.
