### ISSUE TITLE
ENSEMBL IDs

### ISSUE THREAD

**Issue by chrarnold** [churchmanlab/genewalk#3]
Hi, a quick question: Is it possible to support also ENSEMBL IDs as input?

**Comment by chrarnold** [comment]
Hi, I tried to use Ensembl IDs but this is what I got:

`$ genewalk --project cll_test --genes cll_ENSEMBL_IDs_activator_repressor --id_type ensembl_id 
INFO: [2019-09-23 16:12:38] gensim.summarization.textcleaner - 'pattern' package not found; tag filters are not available for English
usage: genewalk [-h] --project PROJECT --genes GENES --id_type
                {hgnc_symbol,hgnc_id,mgi_id}
                [--stage {all,node_vectors,null_distribution,statistics}]
                [--base_folder BASE_FOLDER]
                [--network_source {pc,indra,edge_list,sif}]
                [--network_file NETWORK_FILE] [--nproc NPROC]
                [--nreps_graph NREPS_GRAPH] [--nreps_null NREPS_NULL]
                [--alpha_fdr ALPHA_FDR] [--save_dw SAVE_DW]
                [--random_seed RANDOM_SEED]
genewalk: error: argument --id_type: invalid choice: 'ensembl_id' (choose from 'hgnc_symbol', 'hgnc_id', 'mgi_id')
`

Before, I updated genewalk as described: `pip install git+https://github.com/churchmanlab/genewalk.git`

Also, the missing package warning should not be there, right?

Thanks for your input!

**Comment by bgyori** [comment]
I confirmed that this is working on the latest Github master so I think your pip installation didn't work for some reason. Try making sure that pip forces an update using:
```
pip install -U git+https://github.com/churchmanlab/genewalk.git
```

**Comment by chrarnold** [comment]
You are right, that was it! It looked like it downloaded, but without the -U it nevertheless did not work correctly. Thanks!
