### ISSUE TITLE
INDRA script generation

### ISSUE THREAD

**Issue by xandmac** [churchmanlab/genewalk#42]
Hello, I was looking to explore creating a custom INDRA input. I was wondering if you could provide the script used to create the INDRA network from the paper. 

Thanks!

**Comment by bgyori** [comment]
Hi @xandmac, sorry for the slow response. First of all, here are three Python pickle files that contain INDRA statements for the experiments in the paper:
https://bigmech.s3.amazonaws.com/genewalk/IsoG_HGNCidForINDRA.pkl
https://bigmech.s3.amazonaws.com/genewalk/QKI_MGIforINDRA_stmts.pkl
https://bigmech.s3.amazonaws.com/genewalk/JQ1_HGNCidForINDRA.pkl

In terms of building your own INDRA network, that can take additional work but it gives you flexibility in what kind of relations you want to include from multiple sources. You can see an overview of the knowledge sources that INDRA makes available here: https://github.com/sorgerlab/indra#knowledge-sources, for instance, you might process BioGRID and Signor to get Statements, save it as a pickle file, and pass that to GeneWalk as the `--network_file`. You can also combine this with text mining through one or more of the systems INDRA is integrated with, for instance, Reach. While this takes additional effort to set up, it allows you to derive Statements from subsets of literature that you determine as relevant, and you may relations that are not be available from pathway databases.

**Comment by xandmac** [comment]
Oh thanks for providing the scripts. Very helpful!
