### ISSUE TITLE
GO annotations file comment rows have changed

### ISSUE THREAD

**Issue by bgyori** [churchmanlab/genewalk#60]
In the most recent state of GO annotations there are 41 rows before the actual data starts but we hard coded `skiprows=23` here: https://github.com/churchmanlab/genewalk/blob/master/genewalk/nx_mg_assembler.py#L158 for an older version. We could replace this with a solution that is adaptive and skips all rows starting with `!`.

**Comment by ri23** [comment]
Sounds good!
