### ISSUE TITLE
extending to KEGG

### ISSUE THREAD

**Issue by lli-rice** [churchmanlab/genewalk#73]
Hi,

It's a very cool method. I'm wondering if the method could be extended to enrichment on KEGG terms?

Thanks!

**Comment by ri23** [comment]
Hi,
This should be possible if you assemble a custom network with KEGG and
provide that as input to GeneWalk, with flag

 --network_source {edge_list,sif}

See the documentation for further info.
We have unfortunately no bandwidth to further assist with this.
Best of luck,
Robert
